(function () {
    function Region(code, resolution, countries) {
        this.code = code;
        this.resolution = resolution;
        this.countries = countries || [];
    }
    randomIndex = -1;
    Region.prototype.getRandomCountry = function () {
        //randomIndex = randomIndex + 1;
        //var country = this.countries[randomIndex];
        var country = this.countries[Math.floor(Math.random() * this.countries.length)];
        return country;
    }
    Region.resolutions = {
        countries: "countries",
        provinces: "provinces"
    };

    GeoBattle.Region = Region;

    var regions = {
        northernAfrica: new Region("015", Region.resolutions.countries),
        westernAfrica: new Region("011", Region.resolutions.countries),
        middleAfrica: new Region("017", Region.resolutions.countries),
        easternAfrica: new Region("014", Region.resolutions.countries),
        southernAfrica: new Region("018", Region.resolutions.countries),
        africa: new Region("002", Region.resolutions.countries),
        northernEurope: new Region("154", Region.resolutions.countries),
        westernEurope: new Region("155", Region.resolutions.countries),
        easternEurope: new Region("151", Region.resolutions.countries),
        southernEurope: new Region("039", Region.resolutions.countries),
        europe: new Region("150", Region.resolutions.countries),
        northernAmerica: new Region("021", Region.resolutions.countries),
        caribbean: new Region("029", Region.resolutions.countries),
        centralAmerica: new Region("013", Region.resolutions.countries),
        southAmerica: new Region("005", Region.resolutions.countries),
        americas: new Region("019", Region.resolutions.countries),
        centralAsia: new Region("143", Region.resolutions.countries),
        easternAsia: new Region("030", Region.resolutions.countries),
        southernAsia: new Region("034", Region.resolutions.countries),
        southEasternAsia: new Region("035", Region.resolutions.countries),
        westernAsia: new Region("145", Region.resolutions.countries),
        asia: new Region("142", Region.resolutions.countries),
        australiaAndNewZealand: new Region("053", Region.resolutions.countries),
        melanesia: new Region("054", Region.resolutions.countries),
        micronesia: new Region("057", Region.resolutions.countries),
        polynesia: new Region("061", Region.resolutions.countries),
        oceania: new Region("009", Region.resolutions.countries),
        unitedStates: new Region("US", Region.resolutions.provinces),
        world: new Region("world", Region.resolutions.countries)
    },
    countries = [
        //northern africa
        { code: "DZ", name: "Algeria", regions: [regions.africa, regions.northernAfrica], renderRegion: regions.northernAfrica },
        { code: "EG", name: "Egypt", regions: [regions.africa, regions.northernAfrica], renderRegion: regions.northernAfrica },
        { code: "EH", name: "Western Sahara", regions: [regions.africa, regions.northernAfrica], renderRegion: regions.northernAfrica },
        { code: "LY", name: "Libya", regions: [regions.africa, regions.northernAfrica], renderRegion: regions.northernAfrica },
        { code: "MA", name: "Morocco", regions: [regions.africa, regions.northernAfrica], renderRegion: regions.northernAfrica },
        { code: "SD", name: "Sudan", regions: [regions.africa, regions.northernAfrica], renderRegion: regions.northernAfrica },
        { code: "TN", name: "Tunisia", regions: [regions.africa, regions.northernAfrica], renderRegion: regions.northernAfrica },
        //western africa
        { code: "BF", name: "Burkina Faso", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "BJ", name: "Benin", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "CI", name: "Ivory Coast", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "CV", name: "Cape Verde", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "GH", name: "Ghana", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "GM", name: "Gambia", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "GN", name: "Guinea", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "GW", name: "Guinea-Bissau", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "LR", name: "Liberia", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "ML", name: "Mali", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "MR", name: "Mauritania", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "NE", name: "Niger", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "NG", name: "Nigeria", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "SL", name: "Sierra Leone", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "SN", name: "Senegal", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "TG", name: "Togo", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        //middle africa
        { code: "AO", name: "Angola", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "CD", name: "Congo, the Democratic Republic of the", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "ZR", name: "Zaire", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "CF", name: "Central African Republic", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "CG", name: "Congo", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "CM", name: "Cameroon", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "GA", name: "Gabon", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "GQ", name: "Equatorial Guinea", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "ST", name: "Sao Tome and Principe", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "TD", name: "Chad", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        //eastern africa
        { code: "BI", name: "Burundi", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "DJ", name: "Djibouti", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "ER", name: "Eritrea", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "ET", name: "Eritrea", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "KE", name: "Kenya", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "KM", name: "Comoros", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "MG", name: "Madagascar", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "MU", name: "Mauritius", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "MW", name: "Malawi", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "MZ", name: "Mozambique", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "RE", name: "Réunion", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "RW", name: "Rwanda", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "SC", name: "Seychelles", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "SO", name: "Somalia", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "TZ", name: "Tanzania, United Republic of", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "UG", name: "Uganda", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "YT", name: "Mayotte", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "ZM", name: "Zambia", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "ZW", name: "Zimbabwe", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        //southern africa
        { code: "BW", name: "Botswana", regions: [regions.africa, regions.southernAfrica], renderRegion: regions.southernAfrica },
        { code: "LS", name: "Lesotho", regions: [regions.africa, regions.southernAfrica], renderRegion: regions.southernAfrica },
        { code: "NA", name: "Namibia", regions: [regions.africa, regions.southernAfrica], renderRegion: regions.southernAfrica },
        { code: "SZ", name: "Swaziland", regions: [regions.africa, regions.southernAfrica], renderRegion: regions.southernAfrica },
        { code: "ZA", name: "South Africa", regions: [regions.africa, regions.southernAfrica], renderRegion: regions.southernAfrica },
        //northern europe
        { code: "GG", name: "Guernsey", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "JE", name: "Jersey", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "AX", name: "Åland Islands", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "DK", name: "Denmark", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "EE", name: "Estonia", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "FI", name: "Finland", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "GB", name: "United Kingdom", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "IE", name: "Ireland", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "IM", name: "Isle of Man", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "IS", name: "Iceland", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "LT", name: "Lithuania", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "LV", name: "Latvia", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "NO", name: "Norway", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "SE", name: "Sweden", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "SJ", name: "Svalbard and Jan Mayen", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        //western europe
        { code: "AT", name: "Austria", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "BE", name: "Belgium", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "CH", name: "Switzerland", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "DE", name: "Germany", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "DD", name: "German Democratic Republic", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "FR", name: "France", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "FX", name: "France, Metropolitan", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "LI", name: "Liechtenstein", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "LU", name: "Luxembourg", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "MC", name: "Monaco", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "NL", name: "Netherlands", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        //eastern europe
        { code: "BG", name: "Bulgaria", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "BY", name: "Belarus", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "CZ", name: "Czech Republic", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "HU", name: "Hungary", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "MD", name: "Republic of Moldova", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "PL", name: "Poland", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "RO", name: "Romania", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "RU", name: "Russian Federation", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "SU", name: "USSR", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "SK", name: "Slovakia", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "UA", name: "Ukraine", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        //southern europe
        { code: "AD", name: "Andorra", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "AL", name: "Albania", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "BA", name: "Bosnia and Herzegovina", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "ES", name: "Spain", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "GI", name: "Gibraltar", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "GR", name: "Greece", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "HR", name: "Croatia", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "IT", name: "Italy", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "ME", name: "Montenegro", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "MK", name: "The former Yugoslav Republic of Macedonia", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "MT", name: "Malta", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "CS", name: "Serbia and Montenegro", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "RS", name: "Serbia", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "PT", name: "Portugal", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "SI", name: "Slovenia", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "SM", name: "San Marino", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "VA", name: "Holy See (Vatican City State)", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "YU", name: "Yugoslavia", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        //northern america
        { code: "BM", name: "Bermuda", regions: [regions.americas, regions.northernAmerica], renderRegion: regions.northernAmerica },
        { code: "CA", name: "Canada", regions: [regions.americas, regions.northernAmerica], renderRegion: regions.northernAmerica },
        { code: "GL", name: "Greenland", regions: [regions.americas, regions.northernAmerica], renderRegion: regions.northernAmerica },
        { code: "PM", name: "Saint Pierre and Miquelon", regions: [regions.americas, regions.northernAmerica], renderRegion: regions.northernAmerica },
        { code: "US", name: "United States", regions: [regions.americas, regions.northernAmerica], renderRegion: regions.northernAmerica },
        //caribbean
        { code: "AG", name: "Antigua and Barbuda", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "AI", name: "Anguilla", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "AW", name: "Aruba", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "BB", name: "Barbados", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "BL", name: "Saint Barthélemy", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "BS", name: "Bahamas", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "CU", name: "Cuba", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "DM", name: "Dominica", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "DO", name: "Dominican Republic", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "GD", name: "Grenada", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "GP", name: "Guadeloupe", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "HT", name: "Haiti", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "JM", name: "Jamaica", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "KN", name: "Saint Kitts and Nevis", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "KY", name: "Cayman Islands", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "LC", name: "Saint Lucia", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "MF", name: "Saint Martin (French part)", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "MQ", name: "Martinique", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "MS", name: "Montserrat", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "PR", name: "Puerto Rico", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "TC", name: "Turks and Caicos Islands", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "TT", name: "Trinidad and Tobago", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "VC", name: "Saint Vincent and the Grenadines", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "VG", name: "British Virgin Islands", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "VI", name: "U.S. Virgin Islands", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        //central america
        { code: "BZ", name: "Belize", regions: [regions.americas, regions.centralAmerica], renderRegion: regions.centralAmerica },
        { code: "CR", name: "Costa Rica", regions: [regions.americas, regions.centralAmerica], renderRegion: regions.centralAmerica },
        { code: "GT", name: "Guatemala", regions: [regions.americas, regions.centralAmerica], renderRegion: regions.centralAmerica },
        { code: "HN", name: "Honduras", regions: [regions.americas, regions.centralAmerica], renderRegion: regions.centralAmerica },
        { code: "MX", name: "Mexico", regions: [regions.americas, regions.centralAmerica], renderRegion: regions.centralAmerica },
        { code: "NI", name: "Nicaragua", regions: [regions.americas, regions.centralAmerica], renderRegion: regions.centralAmerica },
        { code: "PA", name: "Panama", regions: [regions.americas, regions.centralAmerica], renderRegion: regions.centralAmerica },
        { code: "SV", name: "El Salvador", regions: [regions.americas, regions.centralAmerica], renderRegion: regions.centralAmerica },
        //south america
        { code: "AR", name: "Argentina", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "BO", name: "Plurinational State of Bolivia", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "BR", name: "Brazil", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "CL", name: "Chile", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "CO", name: "Colombia", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "EC", name: "Ecuador", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "FK", name: "Falkland Islands (Malvinas)", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "GF", name: "French Guiana", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "GY", name: "Guyana", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "PE", name: "Peru", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "PY", name: "Paraguay", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "SR", name: "Suriname", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "UY", name: "Uruguay", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "VE", name: "Bolivarian Republic of Venezuela", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        //central asia
        { code: "TM", name: "Turkmenistan", regions: [regions.asia, regions.centralAsia], renderRegion: regions.centralAsia },
        { code: "TJ", name: "Tajikistan", regions: [regions.asia, regions.centralAsia], renderRegion: regions.centralAsia },
        { code: "KG", name: "Kyrgyzstan", regions: [regions.asia, regions.centralAsia], renderRegion: regions.centralAsia },
        { code: "KZ", name: "Kazakhstan", regions: [regions.asia, regions.centralAsia], renderRegion: regions.centralAsia },
        { code: "UZ", name: "Uzbekistan", regions: [regions.asia, regions.centralAsia], renderRegion: regions.centralAsia },
        //eastern asia
        { code: "CN", name: "China", regions: [regions.asia, regions.easternAsia], renderRegion: regions.easternAsia },
        { code: "HK", name: "Hong Kong", regions: [regions.asia, regions.easternAsia], renderRegion: regions.easternAsia },
        { code: "JP", name: "Japan", regions: [regions.asia, regions.easternAsia], renderRegion: regions.easternAsia },
        { code: "KP", name: "Democratic People's Republic of Korea", regions: [regions.asia, regions.easternAsia], renderRegion: regions.easternAsia },
        { code: "KR", name: "Republic of Korea", regions: [regions.asia, regions.easternAsia], renderRegion: regions.easternAsia },
        { code: "MN", name: "Mongolia", regions: [regions.asia, regions.easternAsia], renderRegion: regions.easternAsia },
        { code: "MO", name: "Macao", regions: [regions.asia, regions.easternAsia], renderRegion: regions.easternAsia },
        { code: "TW", name: "Taiwan", regions: [regions.asia, regions.easternAsia], renderRegion: regions.easternAsia },
        //southern asia
        { code: "AF", name: "Afghanistan", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        { code: "BD", name: "Bangladesh", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        { code: "BT", name: "Bhutan", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        { code: "IN", name: "India", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        { code: "IR", name: "Iran", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        { code: "LK", name: "Sri Lanka", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        { code: "MV", name: "Maldives", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        { code: "NP", name: "Nepal", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        { code: "PK", name: "Pakistan", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        //south eastern asia
        { code: "BN", name: "Brunei Darussalam", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "ID", name: "Indonesia", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "KH", name: "Cambodia", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "LA", name: "Lao People's Democratic Republic", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "MM", name: "Myanmar", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "MY", name: "Malaysia", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "PH", name: "Philippines", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "SG", name: "Singapore", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "TH", name: "Thailand", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "TL", name: "Timor-Leste", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "Vietnam", name: "Country", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        //western asia
        { code: "AE", name: "United Arab Emirates", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "AM", name: "Armenia", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "AZ", name: "Azerbaijan", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "BH", name: "Bahrain", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "CY", name: "Cyprus", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "GE", name: "Georgia", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "IL", name: "Israel", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "IQ", name: "Iraq", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "JO", name: "Jordan", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "KW", name: "Kuwait", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "LB", name: "Lebanon", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "OM", name: "Oman", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "PS", name: "Palestine", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "QA", name: "Qatar", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "SA", name: "Saudi Arabia", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "SY", name: "Syria", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "TR", name: "Turkey", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "YE", name: "Yemen", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        //australia and new zealand
        { code: "AU", name: "Country", regions: [regions.oceania, regions.australiaAndNewZealand], renderRegion: regions.australiaAndNewZealand },
        { code: "NF", name: "Country", regions: [regions.oceania, regions.australiaAndNewZealand], renderRegion: regions.australiaAndNewZealand },
        { code: "NZ", name: "Country", regions: [regions.oceania, regions.australiaAndNewZealand], renderRegion: regions.australiaAndNewZealand },
        //melanesia
        { code: "FJ", name: "Country", regions: [regions.oceania, regions.melanesia], renderRegion: regions.melanesia },
        { code: "NC", name: "Country", regions: [regions.oceania, regions.melanesia], renderRegion: regions.melanesia },
        { code: "PG", name: "Country", regions: [regions.oceania, regions.melanesia], renderRegion: regions.melanesia },
        { code: "SB", name: "Country", regions: [regions.oceania, regions.melanesia], renderRegion: regions.melanesia },
        { code: "VU", name: "Country", regions: [regions.oceania, regions.melanesia], renderRegion: regions.melanesia },
        //micronesia
        { code: "FM", name: "Country", regions: [regions.oceania, regions.micronesia], renderRegion: regions.micronesia },
        { code: "GU", name: "Country", regions: [regions.oceania, regions.micronesia], renderRegion: regions.micronesia },
        { code: "KI", name: "Country", regions: [regions.oceania, regions.micronesia], renderRegion: regions.micronesia },
        { code: "MH", name: "Country", regions: [regions.oceania, regions.micronesia], renderRegion: regions.micronesia },
        { code: "MP", name: "Country", regions: [regions.oceania, regions.micronesia], renderRegion: regions.micronesia },
        { code: "NR", name: "Country", regions: [regions.oceania, regions.micronesia], renderRegion: regions.micronesia },
        { code: "PW", name: "Country", regions: [regions.oceania, regions.micronesia], renderRegion: regions.micronesia },
        //polynesia
        { code: "AS", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "CK", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "NU", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "PF", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "PN", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "TK", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "TO", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "TV", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "WF", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "WS", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        //united states
        { code: "US-AL", name: "Alabama", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-AK", name: "Alaska", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-AZ", name: "Arizona", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-AR", name: "Arkansas", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-CA", name: "California", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-CO", name: "Colorado", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-CT", name: "Connecticut", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-DE", name: "Deleware", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-FL", name: "Florida", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-GA", name: "Georgia", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-HI", name: "Hawaii", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-ID", name: "Idaho", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-IL", name: "Illinois", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-IN", name: "Indiana", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-IA", name: "Iowa", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-KS", name: "Kansas", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-KY", name: "Kentucky", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-LA", name: "Louisiana", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-ME", name: "Massachusetts", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-MD", name: "Maryland", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-MA", name: "Maine", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-MI", name: "Michigan", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-MN", name: "Minnesota", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-MS", name: "Mississippi", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-MO", name: "Missouri", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-MT", name: "Montana", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-NE", name: "Nebraska", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-NV", name: "Nevada", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-NH", name: "New Hampshire", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-NJ", name: "New Jersey", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-NM", name: "New Mexico", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-NY", name: "New York", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-NC", name: "North Carolina", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-ND", name: "North Dakota", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-OH", name: "Ohio", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-OK", name: "Oklahoma", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-OR", name: "Oregon", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-PA", name: "Pennsylvania", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-RI", name: "Rhode Island", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-SC", name: "South Carolina", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-SD", name: "South Dakota", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-TN", name: "Tennessee", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-TX", name: "Texas", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-UT", name: "Utah", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-VT", name: "Vermont", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-VA", name: "Virginia", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-WA", name: "Washington", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-WV", name: "West Virginia", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-WI", name: "Wisconsin", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-WY", name: "Wyoming", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-DC", name: "Washington D.C.", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
    ];

    $.each(countries, function (i, country) {
        var isCountry = false;
        $.each(country.regions, function (j, region) {
            region.countries.push(country);
            if (region.resolution === Region.resolutions.countries) {
                isCountry = true;
            }
        });
        if (isCountry) {
            regions.world.countries.push(country);
        }
    });

    GeoBattle.regions = regions;

})();