(function () {
    function Region(code, resolution, countries) {
        this.code = code;
        this.resolution = resolution;
        this.countries = countries || [];
    }
    randomIndex = -1;
    Region.prototype.getRandomCountry = function () {
        //randomIndex = randomIndex + 1;
        //var country = this.countries[randomIndex];
        var country = this.countries[Math.floor(Math.random() * this.countries.length)];
        return country;
    }
    Region.resolutions = {
        countries: "countries",
        provinces: "provinces"
    };

    GeoBattle.Region = Region;

    var regions = {
        northernAfrica: new Region("015", Region.resolutions.countries),
        westernAfrica: new Region("011", Region.resolutions.countries),
        middleAfrica: new Region("017", Region.resolutions.countries),
        easternAfrica: new Region("014", Region.resolutions.countries),
        southernAfrica: new Region("018", Region.resolutions.countries),
        africa: new Region("002", Region.resolutions.countries),
        northernEurope: new Region("154", Region.resolutions.countries),
        westernEurope: new Region("155", Region.resolutions.countries),
        easternEurope: new Region("151", Region.resolutions.countries),
        southernEurope: new Region("039", Region.resolutions.countries),
        europe: new Region("150", Region.resolutions.countries),
        northernAmerica: new Region("021", Region.resolutions.countries),
        caribbean: new Region("029", Region.resolutions.countries),
        centralAmerica: new Region("013", Region.resolutions.countries),
        southAmerica: new Region("005", Region.resolutions.countries),
        americas: new Region("019", Region.resolutions.countries),
        centralAsia: new Region("143", Region.resolutions.countries),
        easternAsia: new Region("030", Region.resolutions.countries),
        southernAsia: new Region("034", Region.resolutions.countries),
        southEasternAsia: new Region("035", Region.resolutions.countries),
        westernAsia: new Region("145", Region.resolutions.countries),
        asia: new Region("142", Region.resolutions.countries),
        australiaAndNewZealand: new Region("053", Region.resolutions.countries),
        melanesia: new Region("054", Region.resolutions.countries),
        micronesia: new Region("057", Region.resolutions.countries),
        polynesia: new Region("061", Region.resolutions.countries),
        oceania: new Region("009", Region.resolutions.countries),
        unitedStates: new Region("US", Region.resolutions.provinces),
        world: new Region("world", Region.resolutions.countries)
    },
    countries = [
        //northern africa
        { code: "DZ", name: "Algeria", regions: [regions.africa, regions.northernAfrica], renderRegion: regions.northernAfrica },
        { code: "EG", name: "Egypt", regions: [regions.africa, regions.northernAfrica], renderRegion: regions.northernAfrica },
        { code: "EH", name: "Western Sahara", regions: [regions.africa, regions.northernAfrica], renderRegion: regions.northernAfrica },
        { code: "LY", name: "Libya", regions: [regions.africa, regions.northernAfrica], renderRegion: regions.northernAfrica },
        { code: "MA", name: "Morocco", regions: [regions.africa, regions.northernAfrica], renderRegion: regions.northernAfrica },
        { code: "SD", name: "Sudan", regions: [regions.africa, regions.northernAfrica], renderRegion: regions.northernAfrica },
        { code: "TN", name: "Tunisia", regions: [regions.africa, regions.northernAfrica], renderRegion: regions.northernAfrica },
        //western africa
        { code: "BF", name: "Burkina Faso", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "BJ", name: "Benin", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "CI", name: "C�te d'Ivoire", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "CV", name: "Cape Verde", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "GH", name: "Ghana", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "GM", name: "Gambia", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "GN", name: "Guinea", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "GW", name: "Guinea-Bissau", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "LR", name: "Liberia", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "ML", name: "Mali", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "MR", name: "Mauritania", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "NE", name: "Niger", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "NG", name: "Nigeria", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "SL", name: "Sierra Leone", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "SN", name: "Senegal", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        { code: "TG", name: "Togo", regions: [regions.africa, regions.westernAfrica], renderRegion: regions.westernAfrica },
        //middle africa
        { code: "AO", name: "Angola", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "CD", name: "Congo, the Democratic Republic of the", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "ZR", name: "Zaire", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "CF", name: "Central African Republic", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "CG", name: "Congo", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "CM", name: "Cameroon", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "GA", name: "Gabon", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "GQ", name: "Equatorial Guinea", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "ST", name: "Sao Tome and Principe", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        { code: "TD", name: "Chad", regions: [regions.africa, regions.middleAfrica], renderRegion: regions.middleAfrica },
        //eastern africa
        { code: "BI", name: "Burundi", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "DJ", name: "Djibouti", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "ER", name: "Eritrea", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "ET", name: "Eritrea", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "KE", name: "Kenya", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "KM", name: "Comoros", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "MG", name: "Madagascar", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "MU", name: "Mauritius", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "MW", name: "Malawi", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "MZ", name: "Mozambique", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "RE", name: "R�union", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "RW", name: "Rwanda", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "SC", name: "Seychelles", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "SO", name: "Somalia", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "TZ", name: "Tanzania, United Republic of", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "UG", name: "Uganda", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "YT", name: "Mayotte", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "ZM", name: "Zambia", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        { code: "ZW", name: "Zimbabwe", regions: [regions.africa, regions.easternAfrica], renderRegion: regions.easternAfrica },
        //southern africa
        { code: "BW", name: "Botswana", regions: [regions.africa, regions.southernAfrica], renderRegion: regions.southernAfrica },
        { code: "LS", name: "Lesotho", regions: [regions.africa, regions.southernAfrica], renderRegion: regions.southernAfrica },
        { code: "NA", name: "Namibia", regions: [regions.africa, regions.southernAfrica], renderRegion: regions.southernAfrica },
        { code: "SZ", name: "Swaziland", regions: [regions.africa, regions.southernAfrica], renderRegion: regions.southernAfrica },
        { code: "ZA", name: "South Africa", regions: [regions.africa, regions.southernAfrica], renderRegion: regions.southernAfrica },
        //northern europe
        { code: "GG", name: "Guernsey", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "JE", name: "Jersey", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "AX", name: "�land Islands", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "DK", name: "Denmark", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "EE", name: "Estonia", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "FI", name: "Finland", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "GB", name: "United Kingdom", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "IE", name: "Ireland", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "IM", name: "Isle of Man", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "IS", name: "Iceland", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "LT", name: "Lithuania", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "LV", name: "Latvia", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "NO", name: "Norway", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "SE", name: "Sweden", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        { code: "SJ", name: "Svalbard and Jan Mayen", regions: [regions.europe, regions.northernEurope], renderRegion: regions.northernEurope },
        //western europe
        { code: "AT", name: "Austria", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "BE", name: "Belgium", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "CH", name: "Switzerland", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "DE", name: "Germany", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "DD", name: "German Democratic Republic", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "FR", name: "France", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "FX", name: "France, Metropolitan", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "LI", name: "Liechtenstein", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "LU", name: "Luxembourg", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "MC", name: "Monaco", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        { code: "NL", name: "Netherlands", regions: [regions.europe, regions.westernEurope], renderRegion: regions.westernEurope },
        //eastern europe
        { code: "BG", name: "Bulgaria", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "BY", name: "Belarus", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "CZ", name: "Czech Republic", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "HU", name: "Hungary", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "MD", name: "Moldova, Republic of", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "PL", name: "Poland", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "RO", name: "Romania", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "RU", name: "Russian Federation", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "SU", name: "USSR", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "SK", name: "Slovakia", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        { code: "UA", name: "Ukraine", regions: [regions.europe, regions.easternEurope], renderRegion: regions.easternEurope },
        //southern europe
        { code: "AD", name: "Andorra", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "AL", name: "Albania", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "BA", name: "Bosnia and Herzegovina", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "ES", name: "Spain", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "GI", name: "Gibraltar", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "GR", name: "Greece", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "HR", name: "Croatia", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "IT", name: "Italy", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "ME", name: "Montenegro", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "MK", name: "Macedonia, the former Yugoslav Republic of", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "MT", name: "Malta", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "CS", name: "Serbia and Montenegro", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "RS", name: "Serbia", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "PT", name: "Portugal", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "SI", name: "Slovenia", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "SM", name: "San Marino", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "VA", name: "Holy See (Vatican City State)", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        { code: "YU", name: "Yugoslavia", regions: [regions.europe, regions.southernEurope], renderRegion: regions.southernEurope },
        //northern america
        { code: "BM", name: "Country", regions: [regions.americas, regions.northernAmerica], renderRegion: regions.northernAmerica },
        { code: "CA", name: "Country", regions: [regions.americas, regions.northernAmerica], renderRegion: regions.northernAmerica },
        { code: "GL", name: "Country", regions: [regions.americas, regions.northernAmerica], renderRegion: regions.northernAmerica },
        { code: "PM", name: "Country", regions: [regions.americas, regions.northernAmerica], renderRegion: regions.northernAmerica },
        { code: "US", name: "Country", regions: [regions.americas, regions.northernAmerica], renderRegion: regions.northernAmerica },
        //caribbean
        { code: "AG", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "AI", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "AN", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "AW", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "BB", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "BL", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "BS", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "CU", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "DM", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "DO", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "GD", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "GP", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "HT", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "JM", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "KN", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "KY", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "LC", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "MF", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "MQ", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "MS", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "PR", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "TC", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "TT", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "VC", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "VG", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        { code: "VI", name: "Country", regions: [regions.americas, regions.caribbean], renderRegion: regions.caribbean },
        //central america
        { code: "BZ", name: "Country", regions: [regions.americas, regions.centralAmerica], renderRegion: regions.centralAmerica },
        { code: "CR", name: "Country", regions: [regions.americas, regions.centralAmerica], renderRegion: regions.centralAmerica },
        { code: "GT", name: "Country", regions: [regions.americas, regions.centralAmerica], renderRegion: regions.centralAmerica },
        { code: "HN", name: "Country", regions: [regions.americas, regions.centralAmerica], renderRegion: regions.centralAmerica },
        { code: "MX", name: "Country", regions: [regions.americas, regions.centralAmerica], renderRegion: regions.centralAmerica },
        { code: "NI", name: "Country", regions: [regions.americas, regions.centralAmerica], renderRegion: regions.centralAmerica },
        { code: "PA", name: "Country", regions: [regions.americas, regions.centralAmerica], renderRegion: regions.centralAmerica },
        { code: "SV", name: "Country", regions: [regions.americas, regions.centralAmerica], renderRegion: regions.centralAmerica },
        //south america
        { code: "AR", name: "Country", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "BO", name: "Country", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "BR", name: "Country", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "CL", name: "Country", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "CO", name: "Country", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "EC", name: "Country", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "FK", name: "Country", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "GF", name: "Country", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "GY", name: "Country", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "PE", name: "Country", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "PY", name: "Country", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "SR", name: "Country", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "UY", name: "Country", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        { code: "VE", name: "Country", regions: [regions.americas, regions.southAmerica], renderRegion: regions.southAmerica },
        //central asia
        { code: "TM", name: "Country", regions: [regions.asia, regions.centralAsia], renderRegion: regions.centralAsia },
        { code: "TJ", name: "Country", regions: [regions.asia, regions.centralAsia], renderRegion: regions.centralAsia },
        { code: "KG", name: "Country", regions: [regions.asia, regions.centralAsia], renderRegion: regions.centralAsia },
        { code: "KZ", name: "Country", regions: [regions.asia, regions.centralAsia], renderRegion: regions.centralAsia },
        { code: "UZ", name: "Country", regions: [regions.asia, regions.centralAsia], renderRegion: regions.centralAsia },
        //eastern asia
        { code: "CN", name: "Country", regions: [regions.asia, regions.easternAsia], renderRegion: regions.easternAsia },
        { code: "HK", name: "Country", regions: [regions.asia, regions.easternAsia], renderRegion: regions.easternAsia },
        { code: "JP", name: "Country", regions: [regions.asia, regions.easternAsia], renderRegion: regions.easternAsia },
        { code: "KP", name: "Country", regions: [regions.asia, regions.easternAsia], renderRegion: regions.easternAsia },
        { code: "KR", name: "Country", regions: [regions.asia, regions.easternAsia], renderRegion: regions.easternAsia },
        { code: "MN", name: "Country", regions: [regions.asia, regions.easternAsia], renderRegion: regions.easternAsia },
        { code: "MO", name: "Country", regions: [regions.asia, regions.easternAsia], renderRegion: regions.easternAsia },
        { code: "TW", name: "Country", regions: [regions.asia, regions.easternAsia], renderRegion: regions.easternAsia },
        //southern asia
        { code: "AF", name: "Country", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        { code: "BD", name: "Country", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        { code: "BT", name: "Country", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        { code: "IN", name: "Country", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        { code: "IR", name: "Country", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        { code: "LK", name: "Country", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        { code: "MV", name: "Country", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        { code: "NP", name: "Country", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        { code: "PK", name: "Country", regions: [regions.asia, regions.southernAsia], renderRegion: regions.southernAsia },
        //south eastern asia
        { code: "BN", name: "Country", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "ID", name: "Country", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "KH", name: "Country", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "LA", name: "Country", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "MM", name: "Country", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "BU", name: "Country", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "MY", name: "Country", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "PH", name: "Country", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "SG", name: "Country", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "TH", name: "Country", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "TL", name: "Country", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "TP", name: "Country", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        { code: "VN", name: "Country", regions: [regions.asia, regions.southEasternAsia], renderRegion: regions.southEasternAsia },
        //western asia
        { code: "AE", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "AM", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "AZ", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "BH", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "CY", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "GE", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "IL", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "IQ", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "JO", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "KW", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "LB", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "OM", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "PS", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "QA", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "SA", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "NT", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "SY", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "TR", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "YE", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        { code: "YD", name: "Country", regions: [regions.asia, regions.westernAsia], renderRegion: regions.westernAsia },
        //australia and new zealand
        { code: "AU", name: "Country", regions: [regions.oceania, regions.australiaAndNewZealand], renderRegion: regions.australiaAndNewZealand },
        { code: "NF", name: "Country", regions: [regions.oceania, regions.australiaAndNewZealand], renderRegion: regions.australiaAndNewZealand },
        { code: "NZ", name: "Country", regions: [regions.oceania, regions.australiaAndNewZealand], renderRegion: regions.australiaAndNewZealand },
        //melanesia
        { code: "FJ", name: "Country", regions: [regions.oceania, regions.melanesia], renderRegion: regions.melanesia },
        { code: "NC", name: "Country", regions: [regions.oceania, regions.melanesia], renderRegion: regions.melanesia },
        { code: "PG", name: "Country", regions: [regions.oceania, regions.melanesia], renderRegion: regions.melanesia },
        { code: "SB", name: "Country", regions: [regions.oceania, regions.melanesia], renderRegion: regions.melanesia },
        { code: "VU", name: "Country", regions: [regions.oceania, regions.melanesia], renderRegion: regions.melanesia },
        //micronesia
        { code: "FM", name: "Country", regions: [regions.oceania, regions.micronesia], renderRegion: regions.micronesia },
        { code: "GU", name: "Country", regions: [regions.oceania, regions.micronesia], renderRegion: regions.micronesia },
        { code: "KI", name: "Country", regions: [regions.oceania, regions.micronesia], renderRegion: regions.micronesia },
        { code: "MH", name: "Country", regions: [regions.oceania, regions.micronesia], renderRegion: regions.micronesia },
        { code: "MP", name: "Country", regions: [regions.oceania, regions.micronesia], renderRegion: regions.micronesia },
        { code: "NR", name: "Country", regions: [regions.oceania, regions.micronesia], renderRegion: regions.micronesia },
        { code: "PW", name: "Country", regions: [regions.oceania, regions.micronesia], renderRegion: regions.micronesia },
        //polynesia
        { code: "AS", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "CK", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "NU", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "PF", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "PN", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "TK", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "TO", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "TV", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "WF", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        { code: "WS", name: "Country", regions: [regions.oceania, regions.polynesia], renderRegion: regions.polynesia },
        //united states
        { code: "US-AL", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-AK", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-AZ", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-AR", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-CA", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-CO", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-CT", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-DE", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-FL", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-GA", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-HI", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-ID", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-IL", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-IN", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-IA", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-KS", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-KY", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-LA", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-ME", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-MD", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-MA", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-MI", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-MN", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-MS", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-MO", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-MT", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-NE", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-NV", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-NH", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-NJ", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-NM", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-NY", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-NC", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-ND", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-OH", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-OK", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-OR", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-PA", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-RI", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-SC", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-SD", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-TN", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-TX", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-UT", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-VT", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-VA", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-WA", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-WV", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-WI", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-WY", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-DC", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-AS", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-GU", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-MP", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-PR", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-UM", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates },
        { code: "US-VI", name: "State", regions: [regions.unitedStates], renderRegion: regions.unitedStates }
    ];

    $.each(countries, function (i, country) {
        var isCountry = false;
        $.each(country.regions, function (j, region) {
            region.countries.push(country);
            if (region.resolution === Region.resolutions.countries) {
                isCountry = true;
            }
        });
        if (isCountry) {
            regions.world.countries.push(country);
        }
    });

    GeoBattle.regions = regions;

})();